### ISSUE TITLE
Allow to set Bucket Name for Dynamic Volume

### ISSUE THREAD

**Issue by maennchen** [ofek/csi-gcs#10]
Follow up of https://github.com/ofek/csi-gcs/pull/8#issuecomment-615958092

Maybe via annotations in PVC?

**Comment by maennchen** [comment]
This is apparently not intended by the CSI team: https://github.com/kubernetes-csi/external-provisioner/issues/86

Could be read directly from the API though as recommended here: https://github.com/kubernetes-csi/external-provisioner/issues/86#issuecomment-594470291

**Comment by ofek** [comment]
Ah excellent!!!

**Comment by maennchen** [comment]
CLosed in favor of #16
