### ISSUE TITLE
Do I _have_ to specific a service account key or can I use workload id?

### ISSUE THREAD

**Issue by red8888** [ofek/csi-gcs#109]
I run GKE and use workload ID which lets me directly authenticate a Deployment with a GCP service account.

This is transparent to the application as log as it uses the standard credential loading mechanism (ie doesn't explicitly look for creds)

Is the application currently written to only work with a static key placed in a specific k8s secret or can it also retrieve creds implicitly in the standard way (from the GOOGLE_APPLICATION_CREDENTIALS env var, the gke/gce metadata service, etc)

**Comment by ofek** [comment]
> can it also retrieve creds implicitly in the standard way

Yes

- https://ofek.dev/csi-gcs/static_provisioning/#service-account-key
- https://pkg.go.dev/golang.org/x/oauth2/google#FindDefaultCredentials
- https://ofek.dev/csi-gcs/dynamic_provisioning/#permission
