### ISSUE TITLE
Add Support for Snapshots

### ISSUE THREAD

**Issue by maennchen** [ofek/csi-gcs#12]
https://kubernetes-csi.github.io/docs/external-snapshotter.html

**Comment by maennchen** [comment]
For both snapshots & volume content source, files have to be synced via `gsutil rsync` (please mention better ideas :) )

I would recommend that `CreateSnapshot` and also the restoring of a snapshot / from another volume (#13) starts a `Job` with a [`gsutil`](https://github.com/GoogleCloudPlatform/cloud-sdk-docker) container that actually does the copying. The function would block until the call succeeded.

**Comment by ofek** [comment]
Does the Go lib support https://cloud.google.com/storage/docs/moving-buckets#rest-copy-objects?

**Comment by maennchen** [comment]
@ofek One at a time, yes....

**Comment by ofek** [comment]
Should we include gsutil even though it would be large? I'm not a k8s expert but starting a job seems hacky. Is it?

**Comment by maennchen** [comment]
@ofek I don't think that this would be hacky... I think that's a perfect application of K8S.

I would create a separate image only doing that and not package it into the same container.

**Comment by ofek** [comment]
I mean, is it normal for a container to start another container?

**Comment by maennchen** [comment]
For Operators: yes

**Comment by ofek** [comment]
Hmm interesting, okay then 😄

**Comment by maennchen** [comment]
Better Idea:

Instead of waiting minutes to copy small amounts of data via `gsutil`, a `TransferJob` can be created & executed via API. This should be fairly fast and needs no compute power.

https://cloud.google.com/storage-transfer/docs/reference/rest/v1/transferJobs/create

Credit @jeremyzahner

**Comment by ofek** [comment]
Oh very neat. We'd just need to document how to add the required scope to a service account.

**Comment by maennchen** [comment]
Tracked via #47
