### ISSUE TITLE
Use official CSI Release Tools

### ISSUE THREAD

**Issue by maennchen** [ofek/csi-gcs#18]
Use official CSI [release-tools](https://github.com/kubernetes-csi/csi-release-tools) for testing / building.

**Comment by ofek** [comment]
I'm on Windows, so I'd need it to support it. Does it? I quite like the current invoke tooling btw

**Comment by maennchen** [comment]
@ofek I would really like it at least for the E2E tests. It seems very hard to run them otherwise.

We could keep building via invoke but use it to run the tests. What do you think?

Does the driver itself work on Windows btw?

**Comment by ofek** [comment]
Sure! It only works as containerized plugin, not locally (since Windows doesn't have fuse). Docker for Win/Mac provides a Linux VM that everything actually runs in

**Comment by maennchen** [comment]
@ofek How far should the Windows support go then? Only for Building the Image or also testing?

I'm asking because the official test suite including E2E contains a lot of Bash to setup a K8S Cluster correctly etc.

I like the invoke setup as well, I would prefer to stay as close to the spec & official tooling though.

**Comment by ofek** [comment]
Can we run stuff in containers? Building Docker plugins doesn't work on Windows so I run `dind` https://hub.docker.com/_/docker

See https://github.com/ofek/docker-volume-gcs/blob/master/build.py

**Comment by maennchen** [comment]
@ofek I think we could easily do it this way:

* Provide release tools for *NIX users (Makefile)
* Provide a `cmd`/ `bat` / whatever we need for windows that starts all of that inside docker (dind) and calls the `Makefile` in there

**Comment by ofek** [comment]
Sounds good, though why not just do that all the time? Seems cleaner and more reproducible for everyone imo

**Comment by maennchen** [comment]
Why not we can just expose that entrypoint script for Everyone. :)

**Comment by maennchen** [comment]
Setting up `prow` is too much work for not enough benefit for this project.

We'll instead improve the CI (#27) and setup E2E Tests (#28).
