### ISSUE TITLE
Dynamic PVC is not bound

### ISSUE THREAD

**Issue by maennchen** [ofek/csi-gcs#3]
Thanks for this great project, I was waiting a long time for this :heart: 

# Steps

* `kubectl create secret generic csi-gcs-secret -n default --from-literal=bucket=BUCKETNAME --from-file=key=FILENAME`
* `kubectl apply -k "github.com/ofek/csi-gcs/deploy/overlays/stable?ref=master"`
* `kubectl create namespace gcs-example`
* `kubectl create namespace gcs-example2`
* `kubectl apply -k "github.com/ofek/csi-gcs/examples/static?ref=master" -n gcs-example`
* `kubectl apply -k "github.com/ofek/csi-gcs/examples/dynamic?ref=master" -n gcs-example2`

# Outcome

* Static Example works
* Dynamic Example is stuck in `Pending` state

```
Name:          csi-gcs-pvc
Namespace:     gcs-example2
StorageClass:  csi-gcs
Status:        Pending
Volume:        
Labels:        app=csi-gcs-test
Annotations:   volume.beta.kubernetes.io/storage-provisioner: gcs.csi.ofek.dev
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
VolumeMode:    Filesystem
Mounted By:    csi-gcs-test-68dbf75685-bkq99
Events:
  Type    Reason                Age                 From                         Message
  ----    ------                ----                ----                         -------
  Normal  ExternalProvisioning  97s (x42 over 11m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "gcs.csi.ofek.dev" or manually created by system administrator
```

# Logs / additional Info

I could not identify any logs from the `DaemonSet` that looked like they would explain that. (No errors etc.)

**Comment by ofek** [comment]
Thanks for the kind words! Please see https://github.com/ofek/csi-gcs#dynamic-provisioning

**Comment by maennchen** [comment]
@ofek 

I only see mention of this:

> Currently, the buckets used must already exist. PRs adding this ability are extremely welcome!

The bucket mentioned already exists. So that should not be the problem...

(The bucket name is still taken from the secret, right?)

Btw: I'm trying to implement the create bucket functionality. How do you do the local testing / development?

**Comment by ofek** [comment]
Ah okay, well I simply haven't implemented dynamic provisioning then.

For development:

1. get python 3.6+
2. `pip install invoke`
3. `inv build` (dev image name here https://github.com/ofek/csi-gcs/blob/abf292e8779c332ba69a2c58987baa08817eafb1/tasks/__init__.py#L13)
4. `kubectl apply -k deploy\overlays\dev`

**Comment by maennchen** [comment]
@ofek I wrote this down with an easy setup via `minikube` for anyone trying. I'll have a look at automatic creation of the bucket now.

**Comment by ofek** [comment]
Here is an example: https://github.com/ctrox/csi-s3 (this is the opposite of what we do, it _only_ dynamically provisions/creates bucket https://github.com/ctrox/csi-s3/pull/29)

Docs:

- https://github.com/container-storage-interface/spec/blob/master/spec.md
- https://kubernetes-csi.github.io/docs/

More examples (we're listed here too!):

- https://kubernetes-csi.github.io/docs/drivers.html
