### ISSUE TITLE
Leader Election

### ISSUE THREAD

**Issue by maennchen** [ofek/csi-gcs#45]
Switch to use leader election for External Resizer & Provisioner.

This will allow us to a) do everything in the same daemonset and b) have fallbacks if one of the pods would not work as expected.

**Comment by maennchen** [comment]
Example: https://github.com/kubernetes-sigs/blobfuse-csi-driver/pull/87/files

Docs for args:

* https://github.com/kubernetes-csi/external-provisioner#recommended-optional-arguments
* https://github.com/kubernetes-csi/external-resizer#recommended-optional-arguments

**Comment by ofek** [comment]
Woah that's amazing, great idea!!!

**Comment by maennchen** [comment]
Replaced by #46
