### ISSUE TITLE
Failed to acquire lease

### ISSUE THREAD

**Issue by AdheipSingh** [ofek/csi-gcs#57]
Hi Thank you  for this project :) 

I have been using the following command to get started on my gke cluster
```
kubectl apply -k "github.com/ofek/csi-gcs/deploy/overlays/stable?ref=v0.5.0"
```
i am able to mount buckets with readwritemany on multiple pods.
What i am getting is excess info logs after i deploy the daemonset
```
I1101 05:35:53.565206       1 leaderelection.go:326] lock is held by gke-my-gcp-stage-5130c341-kxmk and has not yet expired
I1101 05:35:53.565718       1 leaderelection.go:222] failed to acquire lease kube-system/external-resizer-gcs-csi-ofek-dev
```
As per my debugging **gke-my-gcp-stage-5130c341-kxmk* is a node  in my cluster.
i see this package https://github.com/kubernetes/client-go/blob/9bea17718df8234c2556ffc1ea7416c13effc844/tools/leaderelection/leaderelection.go#L289 which is being used and logging, even with klog level 4 its logging too much ?

Is this behaviour of logs appropriate ? can we reduce the excess logs ? Can we have a flag in csi-gcs to reduce this log ?

**Comment by maennchen** [comment]
@AdheipSingh This is the default functionality of the containers provided by k8s / csi.

You can have a look in their docs / report the issue upstream.

From this projects side, there's not too much we can do I think.

**Comment by AdheipSingh** [comment]
I see makes sense, ill try to open issue upstream and try to get some insights.

Thanks @maennchen
