### ISSUE TITLE
Mount Bucket Not As Root

### ISSUE THREAD

**Issue by AdheipSingh** [ofek/csi-gcs#58]
- When i try to mount my bucket to a path which is having Ownership of a particular USER, the bucket ( pvc ) is not able to mount saying permission denied
- I am able to mount bucket successfully but the owner ship of that path is ROOT
- I am running my process as a USER with UID 1001 , which cannot write to the bucket path since it gets mounted only as ROOT

- Is this behaviour correct that a bucket can only mounted as ROOT ? and we cannot change its permissions what so ever ?
( maybe since gcsfuse need privlege escaltion ? )

**Comment by maennchen** [comment]
https://ofek.dev/csi-gcs/static_provisioning/#extra-flags
