### ISSUE TITLE
Feature request: Workload Identity

### ISSUE THREAD

**Issue by drzero42** [ofek/csi-gcs#60]
It does not seem that csi-gcs supports [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity), which is a very nice feature to avoid handling secret keys and such in GKE.
It would be nice if csi-gcs could support it. It should basically just be to make the specification of a keyfile optional, and then create the client without one. The official Google libs should take care of the rest - if it is running in a Workload Identity enabled cluster, and with a correctly annotated service account it should just use the linked service account to connect to GCS.

**Comment by maennchen** [comment]
@drzero42 I didn't know that this is a thing. This would for sure be a great improvement.

A PR for this would be very welcome.

**Comment by yriveiro** [comment]
With the Workload Identity, the usage of this CSI is highly simplified indeed.

+1 for this one

**Comment by mingoooo** [comment]
@maennchen - I have a PR for this, pls have a look. #67
