### ISSUE TITLE
Support for GCSFuse 0.34.1

### ISSUE THREAD

**Issue by fradeve** [ofek/csi-gcs#68]
Hi,
before everything else, thanks again for your work on this project!

Is there any plan for releasing an updated version csi-gcs that uses [v0.34.1](https://github.com/GoogleCloudPlatform/gcsfuse/releases/tag/v0.34.1) of GCSFuse? The GoogleCloudPlatform made some good progress on some outstanding issues with the upload of large files, and it would be great to take advantage of them in this project as well!

I am mostly referring to:
* https://github.com/GoogleCloudPlatform/gcsfuse/issues/504
* https://github.com/GoogleCloudPlatform/gcsfuse/issues/505

Thanks again!

**Comment by maennchen** [comment]
@fradeve I would gladly accept a PR for this. :+1:

**Comment by fradeve** [comment]
Hi @maennchen, thanks for getting back to me on this :) Sadly we don't have the Go expertise (yet) to help with the work, but if there is anything we could help with (e.g. docs or project management) I will gladly look into it!

**Comment by maennchen** [comment]
I've planned to do some work on this sometime in the future. (Update everything & implement #61 & #47)

I don't have time currently and it will take some time until I get to this.

This was the first project that I ever contributed to in go. I really recommend just trying if you can do it :)

**Comment by ofek** [comment]
@fradeve see: https://github.com/ofek/csi-gcs/pull/63

**Comment by ofek** [comment]
https://github.com/ofek/csi-gcs/pull/70

**Comment by fradeve** [comment]
@ofek I owe you an apology... if I knew this was that easy, I would have done it myself and opened a PR!

**Comment by ofek** [comment]
Ah no worries!
