### ISSUE TITLE
No matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1

### ISSUE THREAD

**Issue by GezimSejdiu** [ofek/csi-gcs#83]
Hi team, 

first of all thanks a lot for this great tool.

While trying to setup I'm constantly getting: 
```
unable to recognize "github.com/ofek/csi-gcs/deploy/overlays/stable?ref=v0.8.0": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
unable to recognize "github.com/ofek/csi-gcs/deploy/overlays/stable?ref=v0.8.0": no matches for kind "CSIDriver" in version "storage.k8s.io/v1beta1"
```
when installing it on GKE. 

I did follow this guide here: https://ofek.dev/csi-gcs/getting_started/ and run: 
```
kubectl apply -k "github.com/ofek/csi-gcs/deploy/overlays/stable?ref=v0.8.0"
```
The `kubectl version` is: 
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.2", GitCommit:"9d142434e3af351a628bffee3939e64c681afa4d", GitTreeState:"clean", BuildDate:"2022-01-19T17:35:46Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.6-gke.300", GitCommit:"df413ee6225aa3fc539e18ca3464a48d723bd3ea", GitTreeState:"clean", BuildDate:"2022-01-24T09:29:08Z", GoVersion:"go1.16.12b7", Compiler:"gc", Platform:"linux/amd64"}
```

Are there any known issues while installing on GKE `v1.22.6-gke.300`? Do I need to upgrade the cluster to get it work?

Thanks a lot in advance for your support.

Best regards, 
Gezim

**Comment by GezimSejdiu** [comment]
Some updates here. I made it work by replacing `apiextensions.k8s.io/v1beta1` with `apiextensions.k8s.io/v1` and `validation` with `schema` and some others as per [this definition](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition).

PS: Let me know if you want to have this as a contribution so that I can push it and you could test it out if that is the way forward. More than happy to push those changes here.

Best regards,

**Comment by omriarieli** [comment]
Hi, we are also facing the same issue although not yet on kubernetes 1.22 we see a warning. it would be nice if a fix can be released.

`kubectl apply -k "github.com/ofek/csi-gcs/deploy/overlays/stable?ref=v0.8.0"
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/publishedvolumes.gcs.csi.ofek.dev created
serviceaccount/csi-gcs created
clusterrole.rbac.authorization.k8s.io/csi-gcs-node created
clusterrole.rbac.authorization.k8s.io/csi-gcs-provisioner created
clusterrole.rbac.authorization.k8s.io/csi-gcs-resizer created
clusterrolebinding.rbac.authorization.k8s.io/csi-gcs-node created
clusterrolebinding.rbac.authorization.k8s.io/csi-gcs-provisioner created
clusterrolebinding.rbac.authorization.k8s.io/csi-gcs-resizer created
daemonset.apps/csi-gcs created
Warning: storage.k8s.io/v1beta1 CSIDriver is deprecated in v1.19+, unavailable in v1.22+; use storage.k8s.io/v1 CSIDriver
csidriver.storage.k8s.io/gcs.csi.ofek.dev created`

**Comment by ofek** [comment]
https://github.com/ofek/csi-gcs/releases/tag/v0.9.0

**Comment by omriarieli** [comment]
thank you so much for the great work @ofek

**Comment by ofek** [comment]
thank you! ❤️
