### ISSUE TITLE
How to add the gcs fuse flags

### ISSUE THREAD

**Issue by elamcheliyana** [ofek/csi-gcs#85]
If I want to pass the argument --implict-dirs in the gcs fuse, How do I achieve?

**Comment by ofek** [comment]
- https://ofek.dev/csi-gcs/static_provisioning/#extra-flags
- https://ofek.dev/csi-gcs/dynamic_provisioning/#extra-flags

**Comment by ofek** [comment]
Got it?

**Comment by elamcheliyana** [comment]
I got it, Thanks for the input
